name: ev_homes
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: ^2.9.1
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  awesome_snackbar_content: ^0.1.3
  font_awesome_flutter: ^10.7.0
  fluentui_system_icons: ^1.1.255
  fl_chart: ^0.69.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  dio: ^5.7.0
  provider: ^6.1.2
  permission_handler: ^11.3.1
  flutter_staggered_grid_view: ^0.7.0
  open_file: ^3.4.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  from_css_color: ^2.0.0
  timeago: ^3.7.0
  json_path: ^0.7.4
  intl: ^0.19.0
  page_transition: ^2.1.0
  auto_size_text: ^3.0.0
  # country_code_picker: ^2.0.2
  multiselect: ^0.1.1
  multiselect_dropdown_flutter: ^0.0.7
  path_provider: ^2.1.4
  syncfusion_flutter_pdfviewer: ^27.1.48
  flutter_riverpod: ^2.0.0
  anim_search_bar: ^2.0.3
  timeline_tile: ^2.0.0
  table_calendar: ^3.1.2
  flutter_native_splash: ^2.4.1
  file_picker: ^8.1.2
  go_router: ^14.2.7
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  csv: ^6.0.0
  collection: ^1.18.0
  syncfusion_flutter_charts: ^27.1.52
  pdf: ^3.11.1
  path: ^1.9.0
  marquee: ^2.3.0
  chewie: ^1.8.5
  flutter_swiper_view: ^1.1.8
  share_plus: ^10.1.1
  animation_search_bar: ^0.0.10
  printing: ^5.6.0
  http: ^1.2.2


  # sending push notifications
  # firebase_core: ^3.6.0
  onesignal_flutter: ^5.2.6
  # storing tokens etc
  flutter_secure_storage: ^9.2.2

  google_sign_in: ^6.2.1
  multi_dropdown: ^3.0.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  workmanager: ^0.5.2
  screenshot: ^3.0.0
  slide_countdown: ^2.0.2
  multi_select_flutter: ^4.1.3
  dropdown_search: ^6.0.1
  dropdown_button2: ^2.3.9
  flutter_date_pickers: ^0.4.3
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/
    - assets/animations/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
